Write your post here.

In [4]:
!conda env list
%matplotlib inline

# conda environments:
#
blog                     /anaconda/envs/blog
pyfolio                  /anaconda/envs/pyfolio
root                  *  /anaconda

In [5]:
#Importing The Data

from pandas_datareader import data
import pandas as pd



# Define the instruments to download. We would like to see Apple, Microsoft and the S&P500 index.
# tickers = ['W', 'HD', 'AMZN','LOW','LL']
tickers = ['ROIC', 'SKT', 'TCO' ,'SPG' ,'MAC']
# Define which online source one should use
data_source = 'yahoo'

# We would like all available data from 01/01/2000 until 12/31/2016.
start_date = '2016-12-01'
end_date = '2017-12-31'

# User pandas_reader.data.DataReader to load the desired data. As simple as that.
panel_data = data.DataReader(tickers, data_source, start_date, end_date)
df = panel_data.ix['Adj Close']

In [12]:
# Basic Description of the Data

df.describe()

first = df.head()
last = df.tail()
print(first)
print(last)

                  MAC       ROIC        SKT         SPG        TCO
Date
2017-12-29  65.680000  19.950001  26.152012  171.740005  65.430000
2017-12-28  66.010002  20.010000  26.142147  171.149994  65.650002
2017-12-27  65.879997  19.780001  25.954712  170.770004  65.709999
2017-12-26  65.730003  19.650000  25.540382  169.360001  65.529999
2017-12-22  65.199997  19.320000  25.066866  167.070007  64.379997
                  MAC       ROIC        SKT         SPG        TCO
Date
2016-12-07  67.464951  20.244057  33.766525  175.889618  70.885620
2016-12-06  65.871819  19.862093  33.173965  172.405350  69.924606
2016-12-05  65.633331  19.795248  32.891792  173.027527  69.087311
2016-12-02  64.994164  19.690208  32.590813  171.687424  68.583031
2016-12-01  64.307297  19.403738  32.261608  169.256088  68.040680

In [27]:
df.sample(6)

                  MAC       ROIC        SKT         SPG        TCO
2017-08-15  54.219425  19.667877  23.887403  155.674820  52.448853
2017-10-16  56.845974  19.034889  24.217821  163.424454  49.627392
2016-12-01  64.307297  19.403738  32.261608  169.256088  68.040680
2017-07-18  57.007412  19.667877  25.669998  156.214249  58.896122
2017-10-03  54.565022  18.817009  24.072048  157.206940  49.300636
2017-12-27  65.879997  19.780001  25.954712  170.770004  65.709999

In [16]:
# A Closer Look At Your Data: Queries

df.query('MAC == ROIC')

Empty DataFrame
Columns: [MAC, ROIC, SKT, SPG, TCO]
Index: []

In [33]:
#cleaning
print(df.columns[df.isnull().any()])

Index([], dtype='object')

In [19]:
# Getting all weekdays between 01/01/2000 and 12/31/2016
all_weekdays = pd.date_range(start=start_date, end=end_date, freq='B')

# How do we align the existing prices in adj_close with our new set of dates?
# All we need to do is reindex adj_close using all_weekdays as the new index
df = df.reindex(all_weekdays)

# Reindexing will insert missing values (NaN) for the dates that were not present
# in the original set. To cope with this, we can fill the missing by replacing them
# with the latest available price for each instrument.
df = df.fillna(method='ffill')
df.isnull()

              MAC   ROIC    SKT    SPG    TCO
2016-12-01  False  False  False  False  False
2016-12-02  False  False  False  False  False
2016-12-05  False  False  False  False  False
2016-12-06  False  False  False  False  False
2016-12-07  False  False  False  False  False
2016-12-08  False  False  False  False  False
2016-12-09  False  False  False  False  False
2016-12-12  False  False  False  False  False
2016-12-13  False  False  False  False  False
2016-12-14  False  False  False  False  False
2016-12-15  False  False  False  False  False
2016-12-16  False  False  False  False  False
2016-12-19  False  False  False  False  False
2016-12-20  False  False  False  False  False
2016-12-21  False  False  False  False  False
2016-12-22  False  False  False  False  False
2016-12-23  False  False  False  False  False
2016-12-26  False  False  False  False  False
2016-12-27  False  False  False  False  False
2016-12-28  False  False  False  False  False
2016-12-29  False  False  False  False  False
2016-12-30  False  False  False  False  False
2017-01-02  False  False  False  False  False
2017-01-03  False  False  False  False  False
2017-01-04  False  False  False  False  False
2017-01-05  False  False  False  False  False
2017-01-06  False  False  False  False  False
2017-01-09  False  False  False  False  False
2017-01-10  False  False  False  False  False
2017-01-11  False  False  False  False  False
...           ...    ...    ...    ...    ...
2017-11-20  False  False  False  False  False
2017-11-21  False  False  False  False  False
2017-11-22  False  False  False  False  False
2017-11-23  False  False  False  False  False
2017-11-24  False  False  False  False  False
2017-11-27  False  False  False  False  False
2017-11-28  False  False  False  False  False
2017-11-29  False  False  False  False  False
2017-11-30  False  False  False  False  False
2017-12-01  False  False  False  False  False
2017-12-04  False  False  False  False  False
2017-12-05  False  False  False  False  False
2017-12-06  False  False  False  False  False
2017-12-07  False  False  False  False  False
2017-12-08  False  False  False  False  False
2017-12-11  False  False  False  False  False
2017-12-12  False  False  False  False  False
2017-12-13  False  False  False  False  False
2017-12-14  False  False  False  False  False
2017-12-15  False  False  False  False  False
2017-12-18  False  False  False  False  False
2017-12-19  False  False  False  False  False
2017-12-20  False  False  False  False  False
2017-12-21  False  False  False  False  False
2017-12-22  False  False  False  False  False
2017-12-25  False  False  False  False  False
2017-12-26  False  False  False  False  False
2017-12-27  False  False  False  False  False
2017-12-28  False  False  False  False  False
2017-12-29  False  False  False  False  False

[282 rows x 5 columns]

In [36]:
# Define your own bins
mybins = range(int(df.MAC.min()), int(df.MAC.max()), 2)

# Cut the data with the help of the bins
df['MAC_bucket'] = pd.cut(df.MAC, bins=mybins)

# Count the number of values per bucket
df['MAC_bucket'].value_counts()

(64, 66]    65
(56, 58]    57
(54, 56]    35
(66, 68]    29
(52, 54]    29
(60, 62]    25
(62, 64]    24
(58, 60]    13
Name: MAC_bucket, dtype: int64